Repository MINI-AGS/mini-test, pull requests merged in 2025-04, with the labels that each got.

#21 11 desarrollar pantallas principales con componentes reutilizables
  App.tsx
  navigator/AppNavigator.tsx
  package-lock.json
  package.json
  screens/EndScreen.tsx
  screens/HomeScreen.tsx
  screens/QuestionsScreen/diagnosis.ts
  screens/QuestionsScreen/module.ts
  screens/QuestionsScreen/questionPage.tsx
  screens/QuestionsScreen/questions.ts
  screens/QuestionsScreen/styles.ts
  screens/QuestionsScreen/types.ts
  styles/FotoPrinciaal.png
  styles/style1.js
  tsconfig copy.json
  tsconfig.json
Labels: enhancement, front🔥🔥🔥🔥🔥

#24 Fix issues of divs in mobile
  package-lock.json
  package.json
  screens/EndScreen.tsx
  screens/HomeScreen.tsx
  screens/QuestionsScreen/questionPage.tsx
Labels: bug

#25 23 kan 27 completar logica de las secciones
  package-lock.json
  package.json
  screens/QuestionsScreen.tsx
  screens/QuestionsScreen/diagnosis.ts
  screens/QuestionsScreen/flags.ts
  screens/QuestionsScreen/module.ts
  screens/QuestionsScreen/questionPage.tsx
  screens/QuestionsScreen/questionRender.ts
  screens/QuestionsScreen/questions.ts
  screens/QuestionsScreen/styles.ts
  screens/QuestionsScreen/types.ts
  screens/QuestionsScreen/utils.ts
Labels: enhancement, front🔥🔥🔥🔥🔥

#60 Better Modal Handling
  screens/QuestionsScreen/_ModalPopup.tsx
  screens/QuestionsScreen/questionPage.tsx
  screens/QuestionsScreen/questions.ts
  screens/QuestionsScreen/styles.ts
  screens/QuestionsScreen/types.ts
  screens/QuestionsScreen/validationutils.ts
  screens/modals/ErrorModal.tsx
  screens/modals/LoadingModal.tsx
  screens/modals/SuccessModal.tsx
Labels: enhancement

#73 Diagnosis now show in the endpage
  App.tsx
  package-lock.json
  package.json
  screens/EndScreen.tsx
  screens/EndScreen/EndScreen.styles.ts
  screens/EndScreen/EndScreen.tsx
  screens/QuestionsScreen/questionPage.tsx
  screens/navigation.ts
Labels: enhancement, front🔥🔥🔥🔥🔥

#74 Update main page
  app.json
  package-lock.json
  package.json
  screens/QuestionsScreen/module.ts
  screens/QuestionsScreen/questionPage.tsx
  screens/QuestionsScreen/styles.ts
  screens/QuestionsScreen/types.ts
Labels: enhancement, front🔥🔥🔥🔥🔥

#79 Remove Debugs and organize some things
  screens/QuestionsScreen/questionPage.tsx
  screens/QuestionsScreen/types.ts
  screens/modals/ErrorModal.tsx
  screens/navigation.ts
Labels: bug

#87 Se arreglo el modulo L, ahora si se muestra, cuenta con su logica par…
  screens/QuestionsScreen/diagnosis.ts
  screens/QuestionsScreen/module.ts
Labels: bug
